# Generated by Django 4.2.1 on 2023-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('dba', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('apartment', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('usdot', models.CharField(blank=True, max_length=250, null=True)),
                ('mc', models.CharField(blank=True, max_length=250, null=True)),
                ('ssn', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_drivers', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_truck', models.CharField(blank=True, max_length=250, null=True)),
                ('type_of_equipment', models.CharField(blank=True, choices=[('Dry_Van', 'Dry Van'), ('Reefer', 'Reefer'), ('Flatbed', 'Flatbed'), ('Box_Truck', 'Box Truck')], max_length=250, null=True)),
                ('factor_invoices', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=250, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('choice_file', models.FileField(blank=True, max_length=254, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Freight_brokers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('lane', models.CharField(blank=True, max_length=250, null=True)),
                ('budget', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('dry_van', models.BooleanField(blank=True, null=True)),
                ('reefer', models.BooleanField(blank=True, null=True)),
                ('flatbed', models.BooleanField(blank=True, null=True)),
                ('box_truck', models.BooleanField(blank=True, null=True)),
                ('number_of_truck', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, verbose_name='имя')),
                ('phone', models.CharField(max_length=250, verbose_name='номер')),
            ],
        ),
    ]
