version: '3.10'

services:
  postgres_db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    container_name: postgres_db

  web:
    build: .
    volumes:
      - ./:/app/
      - ./static:/app/static/
      - ./media:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    container_name: web
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
      image: linuxserver/swag
#      image: nginx:latest
      restart: always
      environment:
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Bishkek
          - URL=
          - SUBDOMAINS=
          - VALIDATION=http
          - ONLY_SUBDOMAINS=true
          - STAGING=false
      depends_on:
          - web
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./nginx/nginx.conf:/config/nginx/site-confs/default.conf
          - ./media:/usr/media/
          - lets:/config/keys/
          - ./static:/usr/static/

volumes:
  postgres_data:
  lets: